services:
  bot:
    container_name: easterobot_bot
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    volumes:
      - ./data:/data:rw
