version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./easterobot/data:/app/easterobot/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro